### ISSUE TITLE
Incorrect arrow indicator

### ISSUE THREAD

**Issue by ipeglin** [sirihelenew/mortensine#6]
The arrows sometimes display ranking relative to first place, and not relative to "local" competitors that you surpass, or is surpassed by.

Example: Here all rankings are displayed as distance from first place, even though the score remains the same for many of the users.
![image](https://github.com/sirihelenew/mortensine/assets/26115581/1d5986cc-eb9d-4603-94eb-96211da91e88)

**Comment by roryff** [comment]
last nights leaderboard data was accidentally deleted. So it should be correct again when i writes tonight...
or if write one manually using current leaderboard ranks now
